
import java.awt.AWTException;
import java.awt.Cursor;
import java.awt.Point;
import java.awt.Robot;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import model.DataHolder;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author abaquitaej
 */
public class MainWindow extends javax.swing.JFrame {

	private DataHolder data;
	Robot robot;
	/**
	 * Creates new form MainWindow
	 */
	public MainWindow() {
		try {
			initComponents();
			data = new DataHolder();
			robot = new Robot();
		} catch (AWTException ex) {
			ex.printStackTrace();
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jDialogRectangle = new javax.swing.JDialog();
        jButtonGetLocation = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jFileChooserDirectory = new javax.swing.JFileChooser();
        jButton2 = new javax.swing.JButton();
        jTextField_Directory = new javax.swing.JTextField();
        jButtonChangeDir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFileListLeft = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableFileListRight = new javax.swing.JTable();
        jButtonTransferRight = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jDialogRectangle.setAlwaysOnTop(true);
        jDialogRectangle.setMinimumSize(new java.awt.Dimension(200, 200));
        jDialogRectangle.setModal(true);
        jDialogRectangle.setPreferredSize(new java.awt.Dimension(400, 400));

        jButtonGetLocation.setText("Get Location");
        jButtonGetLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGetLocationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogRectangleLayout = new javax.swing.GroupLayout(jDialogRectangle.getContentPane());
        jDialogRectangle.getContentPane().setLayout(jDialogRectangleLayout);
        jDialogRectangleLayout.setHorizontalGroup(
            jDialogRectangleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogRectangleLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jButtonGetLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(232, Short.MAX_VALUE))
        );
        jDialogRectangleLayout.setVerticalGroup(
            jDialogRectangleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogRectangleLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jButtonGetLocation)
                .addContainerGap(292, Short.MAX_VALUE))
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);

        jButton2.setText("Locate Output Window");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField_Directory.setEditable(false);

        jButtonChangeDir.setText("Change Directory");
        jButtonChangeDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangeDirActionPerformed(evt);
            }
        });

        jTableFileListLeft.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FileName"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableFileListLeft);

        jButton4.setText("Perform");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTableFileListRight.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FileName"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableFileListRight);

        jButtonTransferRight.setText(">>");
        jButtonTransferRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTransferRightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonChangeDir)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton2)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonTransferRight, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField_Directory, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jTextField_Directory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonChangeDir)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jButtonTransferRight, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
		jDialogRectangle.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonGetLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGetLocationActionPerformed
        // TODO add your handling code here:
		data.setxCoordinate(jDialogRectangle.getX());
		data.setyCoordinate(jDialogRectangle.getY());
		System.out.println("x: "+ jDialogRectangle.getX() + "y: " + jDialogRectangle.getY()) ;
		jDialogRectangle.dispose();
    }//GEN-LAST:event_jButtonGetLocationActionPerformed

    private void jButtonChangeDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangeDirActionPerformed
        // TODO add your handling code here:
		jFileChooserDirectory.setCurrentDirectory(new File("D:/Video_Pipeline_Panther"));
		jFileChooserDirectory.showOpenDialog(this);
		File loc = jFileChooserDirectory.getCurrentDirectory();
		String location  = jFileChooserDirectory.getCurrentDirectory().toString();
		System.out.println(location);
		this.jTextField_Directory.setText(location);
		getAllFiles(loc);
    }//GEN-LAST:event_jButtonChangeDirActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
		robot.mouseMove(data.getxCoordinate(), data.getyCoordinate());
		robot.delay(100);
		leftClick();


		int limit = jTableFileListRight.getRowCount();
		for (int i = 0; i < limit; i++) {
			String data = jTableFileListRight.getValueAt(i, 0).toString();
			String newString = "source " + data;
			type(newString);
			robot.delay(200);
		}

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButtonTransferRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTransferRightActionPerformed
        // TODO add your handling code here:
		int rowNum = jTableFileListLeft.getSelectedRow();
		String value = jTableFileListLeft.getValueAt(rowNum, 0).toString().trim();
		DefaultTableModel table = (DefaultTableModel) jTableFileListRight.getModel(); 
		table.addRow(new Object[]{value});
    }//GEN-LAST:event_jButtonTransferRightActionPerformed

	private void getAllFiles(File file){
		File[] fileList =  file.listFiles();
		for (File f: fileList){
			System.out.println(f.getName());
			populateTable(f.getName());
		}
	}

	private void populateTable(String name){
		DefaultTableModel table = (DefaultTableModel) jTableFileListLeft.getModel(); 
		table.addRow(new Object[]{name});
	}

	private void type(String s){
		        byte[] bytes=s.getBytes();
        for(byte b:bytes)
        {
            int code=b;
            //keycodeonlyhandles[A-Z](whichisASCIIdecimal[65-90])
            if(code>96&&code<123) code=code-32;
			else code = b;
            robot.delay(40);
            robot.keyPress(code);
            robot.keyRelease(code);
        }
		enterKey();
	}

	private void enterKey(){
		robot.delay(40);
		robot.keyPress(KeyEvent.VK_ENTER);
		robot.keyRelease(KeyEvent.VK_ENTER);
	}

	private void leftClick(){
		robot.mousePress(InputEvent.BUTTON1_MASK);
		robot.delay(100);
		robot.mouseRelease(InputEvent.BUTTON1_MASK);
		robot.delay(100);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainWindow().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonChangeDir;
    private javax.swing.JButton jButtonGetLocation;
    private javax.swing.JButton jButtonTransferRight;
    private javax.swing.JDialog jDialogRectangle;
    private javax.swing.JFileChooser jFileChooserDirectory;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTableFileListLeft;
    private javax.swing.JTable jTableFileListRight;
    private javax.swing.JTextField jTextField_Directory;
    // End of variables declaration//GEN-END:variables
}
